// <auto-generated />
namespace Escc.SupportWithConfidence.Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Manage_Categories_With_Entity_Framework : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Manage_Categories_With_Entity_Framework));
        
        string IMigrationMetadata.Id
        {
            get { return "201902271303349_Manage_Categories_With_Entity_Framework"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
