//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Escc.SupportWithConfidence.Controls.AddressFinder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AddressFinderSoap", Namespace="http://www.eastsussex.gov.uk/")]
    public partial class AddressFinder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EastingAndNorthingFromPafAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressesFromPostcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressesFromPartialPostcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressesFromPostcodeAndBuildingNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressesFromPostcodeAndBuildingNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback AggregateEastingsAndNorthingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AggregateEastingsAndNorthingsPartialPostcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AggregateEastingsAndNorthingsBuildingNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback AggregateEastingsAndNorthingsBuildingNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUniqueRoadUSRNGeoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoadNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlaceNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUniquePlaceNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlaceNameDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AddressFinder() {
            this.Url = global::Escc.SupportWithConfidence.Controls.Properties.Settings.Default.Escc_SupportWithConfidence_Controls_AddressFinder_AddressFinder;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EastingAndNorthingFromPafAddressCompletedEventHandler EastingAndNorthingFromPafAddressCompleted;
        
        /// <remarks/>
        public event AddressesFromPostcodeCompletedEventHandler AddressesFromPostcodeCompleted;
        
        /// <remarks/>
        public event AddressesFromPartialPostcodeCompletedEventHandler AddressesFromPartialPostcodeCompleted;
        
        /// <remarks/>
        public event AddressesFromPostcodeAndBuildingNameCompletedEventHandler AddressesFromPostcodeAndBuildingNameCompleted;
        
        /// <remarks/>
        public event AddressesFromPostcodeAndBuildingNumberCompletedEventHandler AddressesFromPostcodeAndBuildingNumberCompleted;
        
        /// <remarks/>
        public event AggregateEastingsAndNorthingsCompletedEventHandler AggregateEastingsAndNorthingsCompleted;
        
        /// <remarks/>
        public event AggregateEastingsAndNorthingsPartialPostcodeCompletedEventHandler AggregateEastingsAndNorthingsPartialPostcodeCompleted;
        
        /// <remarks/>
        public event AggregateEastingsAndNorthingsBuildingNumberCompletedEventHandler AggregateEastingsAndNorthingsBuildingNumberCompleted;
        
        /// <remarks/>
        public event AggregateEastingsAndNorthingsBuildingNameCompletedEventHandler AggregateEastingsAndNorthingsBuildingNameCompleted;
        
        /// <remarks/>
        public event GetUniqueRoadUSRNGeoCompletedEventHandler GetUniqueRoadUSRNGeoCompleted;
        
        /// <remarks/>
        public event GetRoadNamesCompletedEventHandler GetRoadNamesCompleted;
        
        /// <remarks/>
        public event GetPlaceNamesCompletedEventHandler GetPlaceNamesCompleted;
        
        /// <remarks/>
        public event GetUniquePlaceNameCompletedEventHandler GetUniquePlaceNameCompleted;
        
        /// <remarks/>
        public event GetPlaceNameDataCompletedEventHandler GetPlaceNameDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/EastingAndNorthingFromPafAddress", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GeoPoint EastingAndNorthingFromPafAddress(string oid) {
            object[] results = this.Invoke("EastingAndNorthingFromPafAddress", new object[] {
                        oid});
            return ((GeoPoint)(results[0]));
        }
        
        /// <remarks/>
        public void EastingAndNorthingFromPafAddressAsync(string oid) {
            this.EastingAndNorthingFromPafAddressAsync(oid, null);
        }
        
        /// <remarks/>
        public void EastingAndNorthingFromPafAddressAsync(string oid, object userState) {
            if ((this.EastingAndNorthingFromPafAddressOperationCompleted == null)) {
                this.EastingAndNorthingFromPafAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEastingAndNorthingFromPafAddressOperationCompleted);
            }
            this.InvokeAsync("EastingAndNorthingFromPafAddress", new object[] {
                        oid}, this.EastingAndNorthingFromPafAddressOperationCompleted, userState);
        }
        
        private void OnEastingAndNorthingFromPafAddressOperationCompleted(object arg) {
            if ((this.EastingAndNorthingFromPafAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EastingAndNorthingFromPafAddressCompleted(this, new EastingAndNorthingFromPafAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/AddressesFromPostcode", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AddressesFromPostcode(string postCode) {
            object[] results = this.Invoke("AddressesFromPostcode", new object[] {
                        postCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AddressesFromPostcodeAsync(string postCode) {
            this.AddressesFromPostcodeAsync(postCode, null);
        }
        
        /// <remarks/>
        public void AddressesFromPostcodeAsync(string postCode, object userState) {
            if ((this.AddressesFromPostcodeOperationCompleted == null)) {
                this.AddressesFromPostcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressesFromPostcodeOperationCompleted);
            }
            this.InvokeAsync("AddressesFromPostcode", new object[] {
                        postCode}, this.AddressesFromPostcodeOperationCompleted, userState);
        }
        
        private void OnAddressesFromPostcodeOperationCompleted(object arg) {
            if ((this.AddressesFromPostcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressesFromPostcodeCompleted(this, new AddressesFromPostcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/AddressesFromPartialPostcode", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AddressesFromPartialPostcode(string postCode) {
            object[] results = this.Invoke("AddressesFromPartialPostcode", new object[] {
                        postCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AddressesFromPartialPostcodeAsync(string postCode) {
            this.AddressesFromPartialPostcodeAsync(postCode, null);
        }
        
        /// <remarks/>
        public void AddressesFromPartialPostcodeAsync(string postCode, object userState) {
            if ((this.AddressesFromPartialPostcodeOperationCompleted == null)) {
                this.AddressesFromPartialPostcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressesFromPartialPostcodeOperationCompleted);
            }
            this.InvokeAsync("AddressesFromPartialPostcode", new object[] {
                        postCode}, this.AddressesFromPartialPostcodeOperationCompleted, userState);
        }
        
        private void OnAddressesFromPartialPostcodeOperationCompleted(object arg) {
            if ((this.AddressesFromPartialPostcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressesFromPartialPostcodeCompleted(this, new AddressesFromPartialPostcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/AddressesFromPostcodeAndBuildingName", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AddressesFromPostcodeAndBuildingName(string postCode, string buildingName) {
            object[] results = this.Invoke("AddressesFromPostcodeAndBuildingName", new object[] {
                        postCode,
                        buildingName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AddressesFromPostcodeAndBuildingNameAsync(string postCode, string buildingName) {
            this.AddressesFromPostcodeAndBuildingNameAsync(postCode, buildingName, null);
        }
        
        /// <remarks/>
        public void AddressesFromPostcodeAndBuildingNameAsync(string postCode, string buildingName, object userState) {
            if ((this.AddressesFromPostcodeAndBuildingNameOperationCompleted == null)) {
                this.AddressesFromPostcodeAndBuildingNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressesFromPostcodeAndBuildingNameOperationCompleted);
            }
            this.InvokeAsync("AddressesFromPostcodeAndBuildingName", new object[] {
                        postCode,
                        buildingName}, this.AddressesFromPostcodeAndBuildingNameOperationCompleted, userState);
        }
        
        private void OnAddressesFromPostcodeAndBuildingNameOperationCompleted(object arg) {
            if ((this.AddressesFromPostcodeAndBuildingNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressesFromPostcodeAndBuildingNameCompleted(this, new AddressesFromPostcodeAndBuildingNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/AddressesFromPostcodeAndBuildingNumber", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AddressesFromPostcodeAndBuildingNumber(string postCode, string buildingNumber) {
            object[] results = this.Invoke("AddressesFromPostcodeAndBuildingNumber", new object[] {
                        postCode,
                        buildingNumber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AddressesFromPostcodeAndBuildingNumberAsync(string postCode, string buildingNumber) {
            this.AddressesFromPostcodeAndBuildingNumberAsync(postCode, buildingNumber, null);
        }
        
        /// <remarks/>
        public void AddressesFromPostcodeAndBuildingNumberAsync(string postCode, string buildingNumber, object userState) {
            if ((this.AddressesFromPostcodeAndBuildingNumberOperationCompleted == null)) {
                this.AddressesFromPostcodeAndBuildingNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressesFromPostcodeAndBuildingNumberOperationCompleted);
            }
            this.InvokeAsync("AddressesFromPostcodeAndBuildingNumber", new object[] {
                        postCode,
                        buildingNumber}, this.AddressesFromPostcodeAndBuildingNumberOperationCompleted, userState);
        }
        
        private void OnAddressesFromPostcodeAndBuildingNumberOperationCompleted(object arg) {
            if ((this.AddressesFromPostcodeAndBuildingNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressesFromPostcodeAndBuildingNumberCompleted(this, new AddressesFromPostcodeAndBuildingNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/AggregateEastingsAndNorthings", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AggregateEN AggregateEastingsAndNorthings(string postCode) {
            object[] results = this.Invoke("AggregateEastingsAndNorthings", new object[] {
                        postCode});
            return ((AggregateEN)(results[0]));
        }
        
        /// <remarks/>
        public void AggregateEastingsAndNorthingsAsync(string postCode) {
            this.AggregateEastingsAndNorthingsAsync(postCode, null);
        }
        
        /// <remarks/>
        public void AggregateEastingsAndNorthingsAsync(string postCode, object userState) {
            if ((this.AggregateEastingsAndNorthingsOperationCompleted == null)) {
                this.AggregateEastingsAndNorthingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAggregateEastingsAndNorthingsOperationCompleted);
            }
            this.InvokeAsync("AggregateEastingsAndNorthings", new object[] {
                        postCode}, this.AggregateEastingsAndNorthingsOperationCompleted, userState);
        }
        
        private void OnAggregateEastingsAndNorthingsOperationCompleted(object arg) {
            if ((this.AggregateEastingsAndNorthingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AggregateEastingsAndNorthingsCompleted(this, new AggregateEastingsAndNorthingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/AggregateEastingsAndNorthingsPartialPostcode", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AggregateEN AggregateEastingsAndNorthingsPartialPostcode(string partialPostCode) {
            object[] results = this.Invoke("AggregateEastingsAndNorthingsPartialPostcode", new object[] {
                        partialPostCode});
            return ((AggregateEN)(results[0]));
        }
        
        /// <remarks/>
        public void AggregateEastingsAndNorthingsPartialPostcodeAsync(string partialPostCode) {
            this.AggregateEastingsAndNorthingsPartialPostcodeAsync(partialPostCode, null);
        }
        
        /// <remarks/>
        public void AggregateEastingsAndNorthingsPartialPostcodeAsync(string partialPostCode, object userState) {
            if ((this.AggregateEastingsAndNorthingsPartialPostcodeOperationCompleted == null)) {
                this.AggregateEastingsAndNorthingsPartialPostcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAggregateEastingsAndNorthingsPartialPostcodeOperationCompleted);
            }
            this.InvokeAsync("AggregateEastingsAndNorthingsPartialPostcode", new object[] {
                        partialPostCode}, this.AggregateEastingsAndNorthingsPartialPostcodeOperationCompleted, userState);
        }
        
        private void OnAggregateEastingsAndNorthingsPartialPostcodeOperationCompleted(object arg) {
            if ((this.AggregateEastingsAndNorthingsPartialPostcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AggregateEastingsAndNorthingsPartialPostcodeCompleted(this, new AggregateEastingsAndNorthingsPartialPostcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/AggregateEastingsAndNorthingsBuildingNumber", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AggregateEN AggregateEastingsAndNorthingsBuildingNumber(string postCode, string buildingNumber) {
            object[] results = this.Invoke("AggregateEastingsAndNorthingsBuildingNumber", new object[] {
                        postCode,
                        buildingNumber});
            return ((AggregateEN)(results[0]));
        }
        
        /// <remarks/>
        public void AggregateEastingsAndNorthingsBuildingNumberAsync(string postCode, string buildingNumber) {
            this.AggregateEastingsAndNorthingsBuildingNumberAsync(postCode, buildingNumber, null);
        }
        
        /// <remarks/>
        public void AggregateEastingsAndNorthingsBuildingNumberAsync(string postCode, string buildingNumber, object userState) {
            if ((this.AggregateEastingsAndNorthingsBuildingNumberOperationCompleted == null)) {
                this.AggregateEastingsAndNorthingsBuildingNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAggregateEastingsAndNorthingsBuildingNumberOperationCompleted);
            }
            this.InvokeAsync("AggregateEastingsAndNorthingsBuildingNumber", new object[] {
                        postCode,
                        buildingNumber}, this.AggregateEastingsAndNorthingsBuildingNumberOperationCompleted, userState);
        }
        
        private void OnAggregateEastingsAndNorthingsBuildingNumberOperationCompleted(object arg) {
            if ((this.AggregateEastingsAndNorthingsBuildingNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AggregateEastingsAndNorthingsBuildingNumberCompleted(this, new AggregateEastingsAndNorthingsBuildingNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/AggregateEastingsAndNorthingsBuildingName", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AggregateEN AggregateEastingsAndNorthingsBuildingName(string postCode, string buildingName) {
            object[] results = this.Invoke("AggregateEastingsAndNorthingsBuildingName", new object[] {
                        postCode,
                        buildingName});
            return ((AggregateEN)(results[0]));
        }
        
        /// <remarks/>
        public void AggregateEastingsAndNorthingsBuildingNameAsync(string postCode, string buildingName) {
            this.AggregateEastingsAndNorthingsBuildingNameAsync(postCode, buildingName, null);
        }
        
        /// <remarks/>
        public void AggregateEastingsAndNorthingsBuildingNameAsync(string postCode, string buildingName, object userState) {
            if ((this.AggregateEastingsAndNorthingsBuildingNameOperationCompleted == null)) {
                this.AggregateEastingsAndNorthingsBuildingNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAggregateEastingsAndNorthingsBuildingNameOperationCompleted);
            }
            this.InvokeAsync("AggregateEastingsAndNorthingsBuildingName", new object[] {
                        postCode,
                        buildingName}, this.AggregateEastingsAndNorthingsBuildingNameOperationCompleted, userState);
        }
        
        private void OnAggregateEastingsAndNorthingsBuildingNameOperationCompleted(object arg) {
            if ((this.AggregateEastingsAndNorthingsBuildingNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AggregateEastingsAndNorthingsBuildingNameCompleted(this, new AggregateEastingsAndNorthingsBuildingNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/GetUniqueRoadUSRNGeo", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUniqueRoadUSRNGeo(int intRoadUSRN) {
            object[] results = this.Invoke("GetUniqueRoadUSRNGeo", new object[] {
                        intRoadUSRN});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUniqueRoadUSRNGeoAsync(int intRoadUSRN) {
            this.GetUniqueRoadUSRNGeoAsync(intRoadUSRN, null);
        }
        
        /// <remarks/>
        public void GetUniqueRoadUSRNGeoAsync(int intRoadUSRN, object userState) {
            if ((this.GetUniqueRoadUSRNGeoOperationCompleted == null)) {
                this.GetUniqueRoadUSRNGeoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUniqueRoadUSRNGeoOperationCompleted);
            }
            this.InvokeAsync("GetUniqueRoadUSRNGeo", new object[] {
                        intRoadUSRN}, this.GetUniqueRoadUSRNGeoOperationCompleted, userState);
        }
        
        private void OnGetUniqueRoadUSRNGeoOperationCompleted(object arg) {
            if ((this.GetUniqueRoadUSRNGeoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUniqueRoadUSRNGeoCompleted(this, new GetUniqueRoadUSRNGeoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/GetRoadNames", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRoadNames(string roadname) {
            object[] results = this.Invoke("GetRoadNames", new object[] {
                        roadname});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoadNamesAsync(string roadname) {
            this.GetRoadNamesAsync(roadname, null);
        }
        
        /// <remarks/>
        public void GetRoadNamesAsync(string roadname, object userState) {
            if ((this.GetRoadNamesOperationCompleted == null)) {
                this.GetRoadNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoadNamesOperationCompleted);
            }
            this.InvokeAsync("GetRoadNames", new object[] {
                        roadname}, this.GetRoadNamesOperationCompleted, userState);
        }
        
        private void OnGetRoadNamesOperationCompleted(object arg) {
            if ((this.GetRoadNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoadNamesCompleted(this, new GetRoadNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/GetPlaceNames", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPlaceNames(string roadname) {
            object[] results = this.Invoke("GetPlaceNames", new object[] {
                        roadname});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPlaceNamesAsync(string roadname) {
            this.GetPlaceNamesAsync(roadname, null);
        }
        
        /// <remarks/>
        public void GetPlaceNamesAsync(string roadname, object userState) {
            if ((this.GetPlaceNamesOperationCompleted == null)) {
                this.GetPlaceNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlaceNamesOperationCompleted);
            }
            this.InvokeAsync("GetPlaceNames", new object[] {
                        roadname}, this.GetPlaceNamesOperationCompleted, userState);
        }
        
        private void OnGetPlaceNamesOperationCompleted(object arg) {
            if ((this.GetPlaceNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlaceNamesCompleted(this, new GetPlaceNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/GetUniquePlaceName", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUniquePlaceName(string placename, string parishname) {
            object[] results = this.Invoke("GetUniquePlaceName", new object[] {
                        placename,
                        parishname});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUniquePlaceNameAsync(string placename, string parishname) {
            this.GetUniquePlaceNameAsync(placename, parishname, null);
        }
        
        /// <remarks/>
        public void GetUniquePlaceNameAsync(string placename, string parishname, object userState) {
            if ((this.GetUniquePlaceNameOperationCompleted == null)) {
                this.GetUniquePlaceNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUniquePlaceNameOperationCompleted);
            }
            this.InvokeAsync("GetUniquePlaceName", new object[] {
                        placename,
                        parishname}, this.GetUniquePlaceNameOperationCompleted, userState);
        }
        
        private void OnGetUniquePlaceNameOperationCompleted(object arg) {
            if ((this.GetUniquePlaceNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUniquePlaceNameCompleted(this, new GetUniquePlaceNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/GetPlaceNameData", RequestNamespace="http://www.eastsussex.gov.uk/", ResponseNamespace="http://www.eastsussex.gov.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPlaceNameData(string placename) {
            object[] results = this.Invoke("GetPlaceNameData", new object[] {
                        placename});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPlaceNameDataAsync(string placename) {
            this.GetPlaceNameDataAsync(placename, null);
        }
        
        /// <remarks/>
        public void GetPlaceNameDataAsync(string placename, object userState) {
            if ((this.GetPlaceNameDataOperationCompleted == null)) {
                this.GetPlaceNameDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlaceNameDataOperationCompleted);
            }
            this.InvokeAsync("GetPlaceNameData", new object[] {
                        placename}, this.GetPlaceNameDataOperationCompleted, userState);
        }
        
        private void OnGetPlaceNameDataOperationCompleted(object arg) {
            if ((this.GetPlaceNameDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlaceNameDataCompleted(this, new GetPlaceNameDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eastsussex.gov.uk/")]
    public partial class GeoPoint {
        
        private string eastingField;
        
        private string northingField;
        
        /// <remarks/>
        public string Easting {
            get {
                return this.eastingField;
            }
            set {
                this.eastingField = value;
            }
        }
        
        /// <remarks/>
        public string Northing {
            get {
                return this.northingField;
            }
            set {
                this.northingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eastsussex.gov.uk/")]
    public partial class AggregateEN {
        
        private int eastingField;
        
        private int northingField;
        
        /// <remarks/>
        public int Easting {
            get {
                return this.eastingField;
            }
            set {
                this.eastingField = value;
            }
        }
        
        /// <remarks/>
        public int Northing {
            get {
                return this.northingField;
            }
            set {
                this.northingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EastingAndNorthingFromPafAddressCompletedEventHandler(object sender, EastingAndNorthingFromPafAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EastingAndNorthingFromPafAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EastingAndNorthingFromPafAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeoPoint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeoPoint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AddressesFromPostcodeCompletedEventHandler(object sender, AddressesFromPostcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressesFromPostcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressesFromPostcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AddressesFromPartialPostcodeCompletedEventHandler(object sender, AddressesFromPartialPostcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressesFromPartialPostcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressesFromPartialPostcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AddressesFromPostcodeAndBuildingNameCompletedEventHandler(object sender, AddressesFromPostcodeAndBuildingNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressesFromPostcodeAndBuildingNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressesFromPostcodeAndBuildingNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AddressesFromPostcodeAndBuildingNumberCompletedEventHandler(object sender, AddressesFromPostcodeAndBuildingNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressesFromPostcodeAndBuildingNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressesFromPostcodeAndBuildingNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AggregateEastingsAndNorthingsCompletedEventHandler(object sender, AggregateEastingsAndNorthingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AggregateEastingsAndNorthingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AggregateEastingsAndNorthingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AggregateEN Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AggregateEN)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AggregateEastingsAndNorthingsPartialPostcodeCompletedEventHandler(object sender, AggregateEastingsAndNorthingsPartialPostcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AggregateEastingsAndNorthingsPartialPostcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AggregateEastingsAndNorthingsPartialPostcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AggregateEN Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AggregateEN)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AggregateEastingsAndNorthingsBuildingNumberCompletedEventHandler(object sender, AggregateEastingsAndNorthingsBuildingNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AggregateEastingsAndNorthingsBuildingNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AggregateEastingsAndNorthingsBuildingNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AggregateEN Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AggregateEN)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AggregateEastingsAndNorthingsBuildingNameCompletedEventHandler(object sender, AggregateEastingsAndNorthingsBuildingNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AggregateEastingsAndNorthingsBuildingNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AggregateEastingsAndNorthingsBuildingNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AggregateEN Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AggregateEN)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetUniqueRoadUSRNGeoCompletedEventHandler(object sender, GetUniqueRoadUSRNGeoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUniqueRoadUSRNGeoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUniqueRoadUSRNGeoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetRoadNamesCompletedEventHandler(object sender, GetRoadNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoadNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoadNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetPlaceNamesCompletedEventHandler(object sender, GetPlaceNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlaceNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlaceNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetUniquePlaceNameCompletedEventHandler(object sender, GetUniquePlaceNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUniquePlaceNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUniquePlaceNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetPlaceNameDataCompletedEventHandler(object sender, GetPlaceNameDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlaceNameDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlaceNameDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591